// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211020151004_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for product 1",
                            Name = "Product 1",
                            Price = 411m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for product 2",
                            Name = "Product 2",
                            Price = 632m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for product 3",
                            Name = "Product 3",
                            Price = 360m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description for product 4",
                            Name = "Product 4",
                            Price = 215m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description for product 5",
                            Name = "Product 5",
                            Price = 991m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description for product 6",
                            Name = "Product 6",
                            Price = 611m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description for product 7",
                            Name = "Product 7",
                            Price = 854m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description for product 8",
                            Name = "Product 8",
                            Price = 986m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description for product 9",
                            Name = "Product 9",
                            Price = 707m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description for product 10",
                            Name = "Product 10",
                            Price = 717m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Description for product 11",
                            Name = "Product 11",
                            Price = 697m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Description for product 12",
                            Name = "Product 12",
                            Price = 530m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Description for product 13",
                            Name = "Product 13",
                            Price = 277m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Description for product 14",
                            Name = "Product 14",
                            Price = 677m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Description for product 15",
                            Name = "Product 15",
                            Price = 688m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Description for product 16",
                            Name = "Product 16",
                            Price = 567m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Description for product 17",
                            Name = "Product 17",
                            Price = 935m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Description for product 18",
                            Name = "Product 18",
                            Price = 531m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Description for product 19",
                            Name = "Product 19",
                            Price = 902m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Description for product 20",
                            Name = "Product 20",
                            Price = 136m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Description for product 21",
                            Name = "Product 21",
                            Price = 961m
                        },
                        new
                        {
                            Id = 22,
                            Description = "Description for product 22",
                            Name = "Product 22",
                            Price = 998m
                        },
                        new
                        {
                            Id = 23,
                            Description = "Description for product 23",
                            Name = "Product 23",
                            Price = 753m
                        },
                        new
                        {
                            Id = 24,
                            Description = "Description for product 24",
                            Name = "Product 24",
                            Price = 647m
                        },
                        new
                        {
                            Id = 25,
                            Description = "Description for product 25",
                            Name = "Product 25",
                            Price = 934m
                        },
                        new
                        {
                            Id = 26,
                            Description = "Description for product 26",
                            Name = "Product 26",
                            Price = 561m
                        },
                        new
                        {
                            Id = 27,
                            Description = "Description for product 27",
                            Name = "Product 27",
                            Price = 990m
                        },
                        new
                        {
                            Id = 28,
                            Description = "Description for product 28",
                            Name = "Product 28",
                            Price = 569m
                        },
                        new
                        {
                            Id = 29,
                            Description = "Description for product 29",
                            Name = "Product 29",
                            Price = 933m
                        },
                        new
                        {
                            Id = 30,
                            Description = "Description for product 30",
                            Name = "Product 30",
                            Price = 959m
                        },
                        new
                        {
                            Id = 31,
                            Description = "Description for product 31",
                            Name = "Product 31",
                            Price = 118m
                        },
                        new
                        {
                            Id = 32,
                            Description = "Description for product 32",
                            Name = "Product 32",
                            Price = 279m
                        },
                        new
                        {
                            Id = 33,
                            Description = "Description for product 33",
                            Name = "Product 33",
                            Price = 882m
                        },
                        new
                        {
                            Id = 34,
                            Description = "Description for product 34",
                            Name = "Product 34",
                            Price = 469m
                        },
                        new
                        {
                            Id = 35,
                            Description = "Description for product 35",
                            Name = "Product 35",
                            Price = 129m
                        },
                        new
                        {
                            Id = 36,
                            Description = "Description for product 36",
                            Name = "Product 36",
                            Price = 411m
                        },
                        new
                        {
                            Id = 37,
                            Description = "Description for product 37",
                            Name = "Product 37",
                            Price = 837m
                        },
                        new
                        {
                            Id = 38,
                            Description = "Description for product 38",
                            Name = "Product 38",
                            Price = 847m
                        },
                        new
                        {
                            Id = 39,
                            Description = "Description for product 39",
                            Name = "Product 39",
                            Price = 692m
                        },
                        new
                        {
                            Id = 40,
                            Description = "Description for product 40",
                            Name = "Product 40",
                            Price = 937m
                        },
                        new
                        {
                            Id = 41,
                            Description = "Description for product 41",
                            Name = "Product 41",
                            Price = 228m
                        },
                        new
                        {
                            Id = 42,
                            Description = "Description for product 42",
                            Name = "Product 42",
                            Price = 501m
                        },
                        new
                        {
                            Id = 43,
                            Description = "Description for product 43",
                            Name = "Product 43",
                            Price = 789m
                        },
                        new
                        {
                            Id = 44,
                            Description = "Description for product 44",
                            Name = "Product 44",
                            Price = 915m
                        },
                        new
                        {
                            Id = 45,
                            Description = "Description for product 45",
                            Name = "Product 45",
                            Price = 551m
                        },
                        new
                        {
                            Id = 46,
                            Description = "Description for product 46",
                            Name = "Product 46",
                            Price = 720m
                        },
                        new
                        {
                            Id = 47,
                            Description = "Description for product 47",
                            Name = "Product 47",
                            Price = 222m
                        },
                        new
                        {
                            Id = 48,
                            Description = "Description for product 48",
                            Name = "Product 48",
                            Price = 562m
                        },
                        new
                        {
                            Id = 49,
                            Description = "Description for product 49",
                            Name = "Product 49",
                            Price = 607m
                        },
                        new
                        {
                            Id = 50,
                            Description = "Description for product 50",
                            Name = "Product 50",
                            Price = 767m
                        },
                        new
                        {
                            Id = 51,
                            Description = "Description for product 51",
                            Name = "Product 51",
                            Price = 265m
                        },
                        new
                        {
                            Id = 52,
                            Description = "Description for product 52",
                            Name = "Product 52",
                            Price = 467m
                        },
                        new
                        {
                            Id = 53,
                            Description = "Description for product 53",
                            Name = "Product 53",
                            Price = 765m
                        },
                        new
                        {
                            Id = 54,
                            Description = "Description for product 54",
                            Name = "Product 54",
                            Price = 329m
                        },
                        new
                        {
                            Id = 55,
                            Description = "Description for product 55",
                            Name = "Product 55",
                            Price = 622m
                        },
                        new
                        {
                            Id = 56,
                            Description = "Description for product 56",
                            Name = "Product 56",
                            Price = 412m
                        },
                        new
                        {
                            Id = 57,
                            Description = "Description for product 57",
                            Name = "Product 57",
                            Price = 878m
                        },
                        new
                        {
                            Id = 58,
                            Description = "Description for product 58",
                            Name = "Product 58",
                            Price = 713m
                        },
                        new
                        {
                            Id = 59,
                            Description = "Description for product 59",
                            Name = "Product 59",
                            Price = 280m
                        },
                        new
                        {
                            Id = 60,
                            Description = "Description for product 60",
                            Name = "Product 60",
                            Price = 529m
                        },
                        new
                        {
                            Id = 61,
                            Description = "Description for product 61",
                            Name = "Product 61",
                            Price = 621m
                        },
                        new
                        {
                            Id = 62,
                            Description = "Description for product 62",
                            Name = "Product 62",
                            Price = 384m
                        },
                        new
                        {
                            Id = 63,
                            Description = "Description for product 63",
                            Name = "Product 63",
                            Price = 152m
                        },
                        new
                        {
                            Id = 64,
                            Description = "Description for product 64",
                            Name = "Product 64",
                            Price = 747m
                        },
                        new
                        {
                            Id = 65,
                            Description = "Description for product 65",
                            Name = "Product 65",
                            Price = 698m
                        },
                        new
                        {
                            Id = 66,
                            Description = "Description for product 66",
                            Name = "Product 66",
                            Price = 517m
                        },
                        new
                        {
                            Id = 67,
                            Description = "Description for product 67",
                            Name = "Product 67",
                            Price = 647m
                        },
                        new
                        {
                            Id = 68,
                            Description = "Description for product 68",
                            Name = "Product 68",
                            Price = 808m
                        },
                        new
                        {
                            Id = 69,
                            Description = "Description for product 69",
                            Name = "Product 69",
                            Price = 647m
                        },
                        new
                        {
                            Id = 70,
                            Description = "Description for product 70",
                            Name = "Product 70",
                            Price = 377m
                        },
                        new
                        {
                            Id = 71,
                            Description = "Description for product 71",
                            Name = "Product 71",
                            Price = 729m
                        },
                        new
                        {
                            Id = 72,
                            Description = "Description for product 72",
                            Name = "Product 72",
                            Price = 187m
                        },
                        new
                        {
                            Id = 73,
                            Description = "Description for product 73",
                            Name = "Product 73",
                            Price = 838m
                        },
                        new
                        {
                            Id = 74,
                            Description = "Description for product 74",
                            Name = "Product 74",
                            Price = 965m
                        },
                        new
                        {
                            Id = 75,
                            Description = "Description for product 75",
                            Name = "Product 75",
                            Price = 908m
                        },
                        new
                        {
                            Id = 76,
                            Description = "Description for product 76",
                            Name = "Product 76",
                            Price = 560m
                        },
                        new
                        {
                            Id = 77,
                            Description = "Description for product 77",
                            Name = "Product 77",
                            Price = 309m
                        },
                        new
                        {
                            Id = 78,
                            Description = "Description for product 78",
                            Name = "Product 78",
                            Price = 838m
                        },
                        new
                        {
                            Id = 79,
                            Description = "Description for product 79",
                            Name = "Product 79",
                            Price = 196m
                        },
                        new
                        {
                            Id = 80,
                            Description = "Description for product 80",
                            Name = "Product 80",
                            Price = 314m
                        },
                        new
                        {
                            Id = 81,
                            Description = "Description for product 81",
                            Name = "Product 81",
                            Price = 438m
                        },
                        new
                        {
                            Id = 82,
                            Description = "Description for product 82",
                            Name = "Product 82",
                            Price = 528m
                        },
                        new
                        {
                            Id = 83,
                            Description = "Description for product 83",
                            Name = "Product 83",
                            Price = 962m
                        },
                        new
                        {
                            Id = 84,
                            Description = "Description for product 84",
                            Name = "Product 84",
                            Price = 266m
                        },
                        new
                        {
                            Id = 85,
                            Description = "Description for product 85",
                            Name = "Product 85",
                            Price = 794m
                        },
                        new
                        {
                            Id = 86,
                            Description = "Description for product 86",
                            Name = "Product 86",
                            Price = 651m
                        },
                        new
                        {
                            Id = 87,
                            Description = "Description for product 87",
                            Name = "Product 87",
                            Price = 513m
                        },
                        new
                        {
                            Id = 88,
                            Description = "Description for product 88",
                            Name = "Product 88",
                            Price = 653m
                        },
                        new
                        {
                            Id = 89,
                            Description = "Description for product 89",
                            Name = "Product 89",
                            Price = 847m
                        },
                        new
                        {
                            Id = 90,
                            Description = "Description for product 90",
                            Name = "Product 90",
                            Price = 716m
                        },
                        new
                        {
                            Id = 91,
                            Description = "Description for product 91",
                            Name = "Product 91",
                            Price = 532m
                        },
                        new
                        {
                            Id = 92,
                            Description = "Description for product 92",
                            Name = "Product 92",
                            Price = 224m
                        },
                        new
                        {
                            Id = 93,
                            Description = "Description for product 93",
                            Name = "Product 93",
                            Price = 666m
                        },
                        new
                        {
                            Id = 94,
                            Description = "Description for product 94",
                            Name = "Product 94",
                            Price = 263m
                        },
                        new
                        {
                            Id = 95,
                            Description = "Description for product 95",
                            Name = "Product 95",
                            Price = 416m
                        },
                        new
                        {
                            Id = 96,
                            Description = "Description for product 96",
                            Name = "Product 96",
                            Price = 843m
                        },
                        new
                        {
                            Id = 97,
                            Description = "Description for product 97",
                            Name = "Product 97",
                            Price = 448m
                        },
                        new
                        {
                            Id = 98,
                            Description = "Description for product 98",
                            Name = "Product 98",
                            Price = 141m
                        },
                        new
                        {
                            Id = 99,
                            Description = "Description for product 99",
                            Name = "Product 99",
                            Price = 316m
                        },
                        new
                        {
                            Id = 100,
                            Description = "Description for product 100",
                            Name = "Product 100",
                            Price = 133m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Stock = 38
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Stock = 90
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Stock = 7
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Stock = 80
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Stock = 13
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Stock = 67
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Stock = 62
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            Stock = 87
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 9,
                            Stock = 36
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 10,
                            Stock = 18
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 11,
                            Stock = 6
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 12,
                            Stock = 35
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 13,
                            Stock = 62
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 14,
                            Stock = 5
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 15,
                            Stock = 92
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 16,
                            Stock = 79
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 17,
                            Stock = 65
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 18,
                            Stock = 86
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 19,
                            Stock = 52
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 20,
                            Stock = 19
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 21,
                            Stock = 1
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 22,
                            Stock = 11
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 23,
                            Stock = 55
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 24,
                            Stock = 67
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 25,
                            Stock = 5
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 26,
                            Stock = 25
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 27,
                            Stock = 99
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 28,
                            Stock = 31
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 29,
                            Stock = 94
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 30,
                            Stock = 36
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 31,
                            Stock = 31
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 32,
                            Stock = 20
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 33,
                            Stock = 28
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 34,
                            Stock = 12
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 35,
                            Stock = 50
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 36,
                            Stock = 71
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 37,
                            Stock = 94
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 38,
                            Stock = 4
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 39,
                            Stock = 19
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 40,
                            Stock = 53
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 41,
                            Stock = 2
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 42,
                            Stock = 96
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 43,
                            Stock = 76
                        },
                        new
                        {
                            Id = 44,
                            ProductId = 44,
                            Stock = 77
                        },
                        new
                        {
                            Id = 45,
                            ProductId = 45,
                            Stock = 10
                        },
                        new
                        {
                            Id = 46,
                            ProductId = 46,
                            Stock = 2
                        },
                        new
                        {
                            Id = 47,
                            ProductId = 47,
                            Stock = 39
                        },
                        new
                        {
                            Id = 48,
                            ProductId = 48,
                            Stock = 83
                        },
                        new
                        {
                            Id = 49,
                            ProductId = 49,
                            Stock = 15
                        },
                        new
                        {
                            Id = 50,
                            ProductId = 50,
                            Stock = 51
                        },
                        new
                        {
                            Id = 51,
                            ProductId = 51,
                            Stock = 69
                        },
                        new
                        {
                            Id = 52,
                            ProductId = 52,
                            Stock = 19
                        },
                        new
                        {
                            Id = 53,
                            ProductId = 53,
                            Stock = 22
                        },
                        new
                        {
                            Id = 54,
                            ProductId = 54,
                            Stock = 88
                        },
                        new
                        {
                            Id = 55,
                            ProductId = 55,
                            Stock = 94
                        },
                        new
                        {
                            Id = 56,
                            ProductId = 56,
                            Stock = 26
                        },
                        new
                        {
                            Id = 57,
                            ProductId = 57,
                            Stock = 35
                        },
                        new
                        {
                            Id = 58,
                            ProductId = 58,
                            Stock = 40
                        },
                        new
                        {
                            Id = 59,
                            ProductId = 59,
                            Stock = 74
                        },
                        new
                        {
                            Id = 60,
                            ProductId = 60,
                            Stock = 87
                        },
                        new
                        {
                            Id = 61,
                            ProductId = 61,
                            Stock = 67
                        },
                        new
                        {
                            Id = 62,
                            ProductId = 62,
                            Stock = 31
                        },
                        new
                        {
                            Id = 63,
                            ProductId = 63,
                            Stock = 93
                        },
                        new
                        {
                            Id = 64,
                            ProductId = 64,
                            Stock = 99
                        },
                        new
                        {
                            Id = 65,
                            ProductId = 65,
                            Stock = 86
                        },
                        new
                        {
                            Id = 66,
                            ProductId = 66,
                            Stock = 85
                        },
                        new
                        {
                            Id = 67,
                            ProductId = 67,
                            Stock = 7
                        },
                        new
                        {
                            Id = 68,
                            ProductId = 68,
                            Stock = 50
                        },
                        new
                        {
                            Id = 69,
                            ProductId = 69,
                            Stock = 55
                        },
                        new
                        {
                            Id = 70,
                            ProductId = 70,
                            Stock = 21
                        },
                        new
                        {
                            Id = 71,
                            ProductId = 71,
                            Stock = 85
                        },
                        new
                        {
                            Id = 72,
                            ProductId = 72,
                            Stock = 60
                        },
                        new
                        {
                            Id = 73,
                            ProductId = 73,
                            Stock = 66
                        },
                        new
                        {
                            Id = 74,
                            ProductId = 74,
                            Stock = 99
                        },
                        new
                        {
                            Id = 75,
                            ProductId = 75,
                            Stock = 16
                        },
                        new
                        {
                            Id = 76,
                            ProductId = 76,
                            Stock = 4
                        },
                        new
                        {
                            Id = 77,
                            ProductId = 77,
                            Stock = 35
                        },
                        new
                        {
                            Id = 78,
                            ProductId = 78,
                            Stock = 78
                        },
                        new
                        {
                            Id = 79,
                            ProductId = 79,
                            Stock = 56
                        },
                        new
                        {
                            Id = 80,
                            ProductId = 80,
                            Stock = 2
                        },
                        new
                        {
                            Id = 81,
                            ProductId = 81,
                            Stock = 86
                        },
                        new
                        {
                            Id = 82,
                            ProductId = 82,
                            Stock = 16
                        },
                        new
                        {
                            Id = 83,
                            ProductId = 83,
                            Stock = 15
                        },
                        new
                        {
                            Id = 84,
                            ProductId = 84,
                            Stock = 43
                        },
                        new
                        {
                            Id = 85,
                            ProductId = 85,
                            Stock = 67
                        },
                        new
                        {
                            Id = 86,
                            ProductId = 86,
                            Stock = 12
                        },
                        new
                        {
                            Id = 87,
                            ProductId = 87,
                            Stock = 98
                        },
                        new
                        {
                            Id = 88,
                            ProductId = 88,
                            Stock = 39
                        },
                        new
                        {
                            Id = 89,
                            ProductId = 89,
                            Stock = 18
                        },
                        new
                        {
                            Id = 90,
                            ProductId = 90,
                            Stock = 23
                        },
                        new
                        {
                            Id = 91,
                            ProductId = 91,
                            Stock = 35
                        },
                        new
                        {
                            Id = 92,
                            ProductId = 92,
                            Stock = 54
                        },
                        new
                        {
                            Id = 93,
                            ProductId = 93,
                            Stock = 29
                        },
                        new
                        {
                            Id = 94,
                            ProductId = 94,
                            Stock = 31
                        },
                        new
                        {
                            Id = 95,
                            ProductId = 95,
                            Stock = 85
                        },
                        new
                        {
                            Id = 96,
                            ProductId = 96,
                            Stock = 71
                        },
                        new
                        {
                            Id = 97,
                            ProductId = 97,
                            Stock = 3
                        },
                        new
                        {
                            Id = 98,
                            ProductId = 98,
                            Stock = 77
                        },
                        new
                        {
                            Id = 99,
                            ProductId = 99,
                            Stock = 90
                        },
                        new
                        {
                            Id = 100,
                            ProductId = 100,
                            Stock = 24
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
